import type { CommandName } from "./ipc";

// Kept as a literal tuple so TypeScript can prove every typed command is
// represented in the Rust build manifest loaded from ipc-contract.json.
export const IPC_COMMAND_NAMES = [
  "get_supported_keys",
  "get_key_mappings",
  "sync_key_mappings",
  "get_scancode_map_status",
  "apply_scancode_map",
  "restore_scancode_map",
  "upload_image",
  "release_image",
  "list_screenshot_history",
  "get_screenshot_history_image",
  "get_screenshot_history_thumbnail",
  "create_screenshot_history",
  "set_screenshot_history_favorite",
  "delete_screenshot_history",
  "copy_screenshot_history",
  "pin_screenshot_history",
  "get_runtime_health",
  "start_screenshot",
  "start_quick_ocr",
  "close_overlay",
  "show_capture_overlay",
  "overlay_ready",
  "get_full_screenshot",
  "report_capture_rendered",
  "check_screen_permission",
  "copy_image",
  "copy_text",
  "save_image",
  "pin_image",
  "get_pin_image",
  "pin_image_ready",
  "get_pin_options",
  "update_pin_options",
  "copy_pin_image",
  "save_pin_image",
  "close_pin_window",
  "get_pin_window_geometry",
  "set_pin_window_geometry",
  "open_url",
  "get_screenshot_config",
  "update_screenshot_config",
  "update_screenshot_annotation_color",
  "update_screenshot_annotation_outline",
  "update_screenshot_annotation_styles",
  "get_screenshot_shortcut_statuses",
  "reset_screenshot_shortcuts",
  "choose_screenshot_save_directory",
  "export_diagnostics",
  "recognize_selection",
  "get_color_palette",
  "record_palette_color",
  "set_palette_favorite",
  "clear_recent_palette",
  "decode_qr_selection",
  "refresh_widget_position",
  "get_widget_config",
  "update_widget_config",
  "sync_widget_dynamic_width",
  "key_visualizer_ready",
  "get_key_visualizer_session",
  "get_key_visualizer_effects_status",
  "locate_key_visualizer_mouse",
  "key_visualizer_effects_ready",
  "get_key_visualizer_config",
  "update_key_visualizer_config",
  "get_key_visualizer_status",
  "retry_key_visualizer",
  "get_minimize_to_tray",
  "set_minimize_to_tray",
] as const satisfies readonly CommandName[];

type MissingTypedCommand = Exclude<CommandName, (typeof IPC_COMMAND_NAMES)[number]>;
const allTypedCommandsAreDeclared: MissingTypedCommand extends never ? true : never = true;
void allTypedCommandsAreDeclared;
