import { useCallback, useEffect, useState } from "react";
import { listen } from "@tauri-apps/api/event";
import { Alert, Button, Card, Form, InputNumber, Select, Space, Spin, Switch, Tag, Typography, message } from "antd";
import { errorMessage, keyVisualizerApi, MAIN_EVENTS } from "../api/commands";
import type { KeyVisualizerConfig, KeyVisualizerStatus } from "../types";
import styles from "./components.module.scss";

type KeyFormValues = Omit<KeyVisualizerConfig, "show_modifiers" | "show_combinations" | "show_characters" | "show_other"> & { categories: string[] };
const toForm = (config: KeyVisualizerConfig): KeyFormValues => ({ ...config, categories: [["modifiers", config.show_modifiers], ["combinations", config.show_combinations], ["characters", config.show_characters], ["other", config.show_other]].filter(([, enabled]) => enabled).map(([name]) => name) as string[] });
const toConfig = (values: KeyFormValues): KeyVisualizerConfig => {
  const { categories: selectedCategories = [], ...config } = values;
  return { ...config, show_modifiers: selectedCategories.includes("modifiers"), show_combinations: selectedCategories.includes("combinations"), show_characters: selectedCategories.includes("characters"), show_other: selectedCategories.includes("other") };
};

export default function KeyVisualizerSettings({ disabled = false }: { disabled?: boolean }) {
  const [form] = Form.useForm<KeyFormValues>(); const [saved, setSaved] = useState<KeyVisualizerConfig | null>(null); const [status, setStatus] = useState<KeyVisualizerStatus | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [loadError, setLoadError] = useState<string | null>(null); const values = Form.useWatch([], form);
  const load = useCallback(async () => { setLoading(true); setLoadError(null); try { const [config, nextStatus] = await Promise.all([keyVisualizerApi.config(), keyVisualizerApi.status()]); setSaved(config); form.setFieldsValue(toForm(config)); form.resetFields(); setStatus(nextStatus); } catch (error) { setLoadError(errorMessage(error)); } finally { setLoading(false); } }, [form]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { let disposed = false; let off: (() => void) | undefined; void listen<KeyVisualizerConfig>(MAIN_EVENTS.keyVisualizerConfigChanged, ({ payload }) => { if (!disposed) { setSaved(payload); form.setFieldsValue(toForm(payload)); form.resetFields(); } }).then((unlisten) => { if (disposed) unlisten(); else off = unlisten; }).catch((reason) => { if (!disposed) setLoadError(`监听按键设置失败：${errorMessage(reason)}`); }); return () => { disposed = true; off?.(); }; }, [form]);
  if (loading) return <div className={styles.centerState}><Spin tip="读取按键文本设置…" /></div>;
  if (loadError || !saved) return <Alert type="error" showIcon message="按键文本设置读取失败" description={loadError} action={<Button onClick={() => void load()}>重试</Button>} />;
  const dirty = JSON.stringify(toConfig(values ?? toForm(saved))) !== JSON.stringify(saved);
  const save = async (next: KeyFormValues) => { setSaving(true); try { const config = await keyVisualizerApi.update(toConfig(next)); setSaved(config); form.setFieldsValue(toForm(config)); form.resetFields(); setStatus(await keyVisualizerApi.status()); message.success("按键展示设置已保存"); } catch (error) { message.error(`按键文本设置未保存：${errorMessage(error)}`); } finally { setSaving(false); } };
  return <Form form={form} layout="vertical" className={styles.settingsForm} disabled={disabled || saving} onFinish={(next) => void save(next)}>
    <Card className={styles.glassCard} bordered={false}><div className={styles.sectionHeader}><div><Typography.Title level={4}>普通按键展示</Typography.Title><Typography.Text type="secondary">只显示键帽名称，不解析输入内容，也不会记录或上传。</Typography.Text></div><Space><Tag color={status?.listening ? "success" : saved.enabled ? "error" : "default"}>{status?.listening ? "原生监听中" : saved.enabled ? "监听异常" : "已停用"}</Tag><Form.Item noStyle name="enabled" valuePropName="checked"><Switch checkedChildren="显示" unCheckedChildren="隐藏" /></Form.Item></Space></div>{status?.error && <Alert className={styles.inlineAlert} type="error" showIcon message="原生监听启动失败" description={status.error} action={<Button size="small" disabled={disabled} onClick={() => void keyVisualizerApi.retry().then(setStatus).catch((error) => message.error(errorMessage(error)))}>重试</Button>} />}</Card>
    <Card className={styles.glassCard} bordered={false} title="展示内容"><Form.Item name="categories"><Select mode="multiple" showSearch={false} placeholder="请选择需展示的按键类别" className={styles.multiSelect} options={[{ value: "modifiers", label: "修饰键" }, { value: "combinations", label: "组合键" }, { value: "characters", label: "字符键" }, { value: "other", label: "其他键" }]} /></Form.Item></Card>
    <Card className={styles.glassCard} bordered={false} title="显示与交互"><div className={styles.numericConfigGrid}><div className={styles.numericConfigItem}><div><Typography.Text strong>字号</Typography.Text><span className={styles.description}>16–48 px</span></div><Form.Item name="font_size" rules={[{ required: true, type: "number", min: 16, max: 48, message: "字号需在 16–48 px 之间" }]}><InputNumber min={16} max={48} suffix="px" /></Form.Item></div><div className={styles.numericConfigItem}><div><Typography.Text strong>整体缩放</Typography.Text><span className={styles.description}>75–200%</span></div><Form.Item name="scale_percent" rules={[{ required: true, type: "number", min: 75, max: 200, message: "缩放需在 75–200% 之间" }]}><InputNumber min={75} max={200} step={5} suffix="%" /></Form.Item></div><div className={styles.numericConfigItem}><div><Typography.Text strong>文本透明度</Typography.Text><span className={styles.description}>20–100%</span></div><Form.Item name="text_opacity" rules={[{ required: true, type: "number", min: 20, max: 100, message: "透明度需在 20–100% 之间" }]}><InputNumber min={20} max={100} step={5} suffix="%" /></Form.Item></div></div><Space><Button type="primary" htmlType="submit" loading={saving} disabled={!dirty}>保存普通按键设置</Button><Button disabled={saving || !dirty} onClick={() => { form.setFieldsValue(toForm(saved)); form.resetFields(); }}>撤销修改</Button></Space></Card>
  </Form>;
}
