import {
  ArrowUpRight,
  Circle,
  PenLine,
  Square,
  Diamond,
  Eraser,
  Minus,
  MousePointer2,
  Type,
  Highlighter,
  Grid2X2,
  Pipette,
  ListOrdered,
} from "lucide-react";
export const screenshotToolIcons = {
  select: MousePointer2,
  rect: Square,
  arrow: ArrowUpRight,
  pen: PenLine,
  text: Type,
  mosaic: Grid2X2,
  ellipse: Circle,
  diamond: Diamond,
  line: Minus,
  highlight: Highlighter,
  picker: Pipette,
  number: ListOrdered,
  eraser: Eraser,
};
